/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 포트폴리오 생성
         * @description 포트폴리오 생성
         */
        post: operations["portfolio-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 시스템 헬스 체크
         * @description DB, Redis, Kafka의 연결 상태를 통합 조회합니다.
         */
        get: operations["admin-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 소셜 로그인 정보를 통해 액세스 토큰 및 리프레시 토큰을 발급받습니다.
         */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 서버에서 리프레시 토큰을 삭제합니다.
         */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description 리프레시 토큰을 사용하여 새로운 액세스 토큰을 발급받습니다.
         */
        post: operations["auth-reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 포트폴리오 상세 조회
         * @description 포트폴리오 상세 조회
         */
        get: operations["portfolio-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/new-listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 신규 상장 종목 조회
         * @description 신규 상장 종목 조회
         */
        get: operations["stock-new-listings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/popular-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 인기 검색어 조회
         * @description 인기 검색어 조회
         */
        get: operations["stock-popular-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 종목 통합 검색
         * @description 티커 또는 종목명으로 주식을 검색합니다.
         */
        get: operations["stock-search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관심 그룹 목록 조회
         * @description 관심 그룹 목록 조회
         */
        get: operations["watchlist-group-list"];
        put?: never;
        /**
         * 관심 그룹 생성
         * @description 관심 그룹 생성
         */
        post: operations["watchlist-group-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sectors/ranking/fluctuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 섹터 등락률 랭킹 조회
         * @description 지정된 날짜의 섹터별 등락률 순위를 조회합니다.
         */
        get: operations["sector-ranking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sectors/ranking/supply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 섹터 수급 랭킹 조회
         * @description 외국인/기관 순매수 금액 및 연속 매수 일수 기반의 섹터 순위를 조회합니다.
         */
        get: operations["sector-supply"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sectors/{sectorCode}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 섹터 상세 정보 조회
         * @description 특정 섹터의 상세 인사이트, 기술적 지표, 주도주 정보를 조회합니다.
         */
        get: operations["sector-detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/search/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 검색어 조회
         * @description 최근 검색어 조회
         */
        get: operations["stock-search-history"];
        put?: never;
        post?: never;
        /**
         * 최근 검색어 개별 삭제
         * @description 최근 검색어 개별 삭제
         */
        delete: operations["stock-search-history-delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{ticker}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 종목 수익률 조회
         * @description 종목 수익률 조회
         */
        get: operations["stock-returns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/advice/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최신 AI 리밸런싱 조언 조회
         * @description 최신 AI 리밸런싱 조언 조회
         */
        get: operations["portfolio-advice-latest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/analysis/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 포트폴리오 과거 백테스팅
         * @description 포트폴리오 과거 백테스팅
         */
        post: operations["portfolio-analysis-backtest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/analysis/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 포트폴리오 종목 간 상관관계 분석
         * @description 포트폴리오 종목 간 상관관계 분석
         */
        get: operations["portfolio-analysis-correlation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/analysis/diversification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 포트폴리오 자산 분산도 분석
         * @description 포트폴리오 자산 분산도 분석
         */
        get: operations["portfolio-analysis-diversification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/analysis/rebalancing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 포트폴리오 리밸런싱 분석
         * @description 포트폴리오 리밸런싱 분석
         */
        get: operations["portfolio-analysis-rebalancing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/analysis/valuation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 포트폴리오 자산 가치 분석
         * @description 포트폴리오 자산 가치 분석
         */
        get: operations["portfolio-analysis-value"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/search/history/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 최근 검색어 전체 삭제
         * @description 최근 검색어 전체 삭제
         */
        delete: operations["stock-search-history-clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{ticker}/prices/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 차트용 시세 데이터 조회
         * @description 차트용 시세 데이터 조회
         */
        get: operations["stock-price-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/groups/{groupId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관심 종목 목록 조회
         * @description 관심 종목 목록 조회
         */
        get: operations["watchlist-item-list"];
        put?: never;
        /**
         * 관심 종목 추가
         * @description 관심 종목 추가
         */
        post: operations["watchlist-item-add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/groups/{groupId}/items/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 관심 종목 제거
         * @description 관심 종목 제거
         */
        delete: operations["watchlist-item-remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/groups/{groupId}/items/{ticker}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 관심 종목 메모 수정
         * @description 관심 종목 메모 수정
         */
        patch: operations["watchlist-item-note-update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** LoginRequest */
        LoginRequest: {
            /** @description 로그인 타입 (GOOGLE, KAKAO, NAVER) */
            loginType: string;
            /** @description 닉네임 */
            nickname: string;
            /** @description 이메일 */
            email: string;
        };
        /** SectorRankingResponse */
        SectorRankingResponse: {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 섹터 랭킹 리스트 */
            data: {
                /** @description 섹터 코드 */
                sectorCode: string;
                /** @description 평균 등락률 */
                fluctuationRate: number;
                /** @description 현재 지수 */
                currentPrice: number;
                /** @description 섹터명 */
                sectorName: string;
                /** @description 과열 여부 */
                isOverheated: boolean;
            }[];
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-portfolioId-analysis-backtest695967913": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description AI 분석 코멘트 */
                aiComment?: string | null;
                /** @description 총 수익률 */
                totalReturnRate: number;
                dailyResults?: {
                    /** @description 총 가치 */
                    totalValue: number;
                    /** @description 날짜 */
                    date: string;
                    /** @description 벤치마크 수익률 (%) */
                    benchmarkReturnRate: number;
                    /** @description 누적 수익률 (%) */
                    returnRate: number;
                    /** @description 총 투자금 */
                    totalInvested: number;
                }[];
                /** @description 초과 수익률 (Alpha) */
                alpha: number;
                /** @description 연평균 수익률 (CAGR) */
                cagr: number;
                /** @description 변동성 */
                volatility: number;
                /** @description 샤프 지수 */
                sharpeRatio: number;
                /** @description 최고의 해 수익률 */
                bestYearRate: number;
                /** @description 최대 낙폭 (MDD) */
                mdd: number;
                /** @description 시장 민감도 (Beta) */
                beta: number;
                /** @description 최악의 해 수익률 */
                worstYearRate: number;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** EmptyDataResponse */
        EmptyDataResponse: {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-stocks-search-1069080236": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 현재 페이지 번호 */
                number: number;
                /** @description 페이지 사이즈 */
                size: number;
                /** @description 현재 페이지 엘리먼트 수 */
                numberOfElements: number;
                /** @description 마지막 페이지 여부 */
                last: boolean;
                /** @description 페이징 정보 */
                pageable: string;
                sort?: {
                    /** @description 미정렬 여부 */
                    unsorted: boolean;
                    /** @description 정렬 여부 */
                    sorted: boolean;
                    /** @description 정렬 정보 비어있음 여부 */
                    empty: boolean;
                };
                /** @description 첫 번째 페이지 여부 */
                first: boolean;
                content?: {
                    /** @description 티커 */
                    ticker: string;
                    /** @description 종목명 */
                    name: string;
                    /** @description 섹터명 */
                    sectorName: string;
                    /** @description 마켓 타입 */
                    marketType: string;
                    /** @description 종목 상태 */
                    status: string;
                }[];
                /** @description 결과 비어있음 여부 */
                empty: boolean;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-stocks-ticker-prices-history-112452904": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 티커 */
                ticker: string;
                /** @description 종목명 */
                stockName: string;
                /** @description 벤치마크 데이터 목록 */
                benchmarks: (Record<string, never> | boolean | string | number)[];
                prices?: {
                    /** @description 20일 이동평균선 */
                    ma20?: number | null;
                    /** @description 5일 이동평균선 */
                    ma5?: number | null;
                    /** @description 거래량 */
                    volume: number;
                    /** @description 날짜 */
                    date: string;
                    /** @description 거래대금 */
                    transactionAmt?: number | null;
                    /** @description 고가 */
                    high: number;
                    /** @description 수정종가 */
                    adjClose: number;
                    /** @description 저가 */
                    low: number;
                    /** @description 120일 이동평균선 */
                    ma120?: number | null;
                    /** @description 60일 이동평균선 */
                    ma60?: number | null;
                    /** @description 종가 */
                    close: number;
                    /** @description 시가 */
                    open: number;
                }[];
                /** @description 벤치마크 이름 (ex: KOSPI, S&P 500) */
                benchmarkName: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-watchlist-groups-groupId-items-775687594": {
            /** @description 투자 메모 (선택) */
            note: string;
            /** @description 종목 티커 */
            ticker: string;
        };
        /** SectorDetailResponse */
        SectorDetailResponse: {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 주도주 리스트 */
                leadingStocks: {
                    /** @description 주도주 거래량 */
                    tradeVolume: number;
                    /** @description 주도주 거래대금 */
                    transactionAmt: number;
                    /** @description 주도주 티커 */
                    ticker: string;
                    /** @description 주도주 등락률 */
                    fluctuationRate: number;
                    /** @description 주도주 명 */
                    name: string;
                }[];
                /** @description 기준 날짜 */
                baseDate: string;
                /** @description 상세 진단 메시지 */
                diagnosisMessage: string;
                /** @description 기술적 지표 */
                technicalIndicators?: {
                    /** @description 20일 이동평균선 */
                    ma20?: number | null;
                    /** @description 5일 이동평균선 */
                    ma5?: number | null;
                    /** @description RSI(14) 지표 */
                    rsi14?: number | null;
                };
                /** @description 섹터 코드 */
                sectorCode: string;
                /** @description 평균 등락률 */
                fluctuationRate: number;
                /** @description 현재 지수 */
                currentPrice: number;
                /** @description 섹터명 */
                sectorName: string;
                /** @description 과열 진단 여부 */
                isOverheated: boolean;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-watchlist-groups15903716": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 그룹 이름 */
                name: string;
                /** @description 그룹 ID */
                id: number;
                /** @description 포함된 종목 수 */
                itemCount: number;
            }[];
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** ReissueRequest */
        ReissueRequest: {
            /** @description 리프레시 토큰 */
            refreshToken: string;
        };
        "api-v1-stocks-search-history486549215": Record<string, never>;
        "api-v1-stocks-popular-search-808622291": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 인기 검색어 목록 */
            data: (Record<string, never> | boolean | string | number)[];
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** LoginResponse */
        LoginResponse: {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 닉네임 */
                nickname: string;
                /** @description 액세스 토큰 */
                accessToken: string;
                /** @description 이메일 */
                email: string;
                /** @description 가입 일자 */
                joinedDate: string;
                /** @description 회원 ID */
                memberId: number;
                /** @description 리프레시 토큰 */
                refreshToken: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** ReissueResponse */
        ReissueResponse: {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 새로운 액세스 토큰 */
                accessToken: string;
                /** @description 새로운 리프레시 토큰 */
                refreshToken: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-portfolioId-analysis-diversification-1682980467": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 총 자산 가치 */
                totalValue: number;
                countryRatios?: {
                    /** @description 국가 명칭 */
                    name: string;
                    /** @description 비중 (%) */
                    value: number;
                }[];
                sectorRatios?: {
                    /** @description 섹터 명칭 */
                    name: string;
                    /** @description 비중 (%) */
                    value: number;
                }[];
                assetRatios?: {
                    /** @description 자산군 명칭 */
                    name: string;
                    /** @description 비중 (%) */
                    value: number;
                }[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-watchlist-groups288370516": {
            /** @description 그룹 이름 */
            name: string;
        };
        "api-v1-stocks-new-listings562932331": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 티커 */
                ticker: string;
                /** @description 종목명 */
                name: string;
                /** @description 섹터명 */
                sectorName: string;
                /** @description 마켓 타입 */
                marketType: string;
                /** @description 종목 상태 */
                status: string;
            }[];
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-portfolioId-advice-latest-337529530": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 생성 일시 */
                createdAt: string;
                /** @description 핵심 조언 액션 */
                action: string;
                /** @description 상세 조언 내용 */
                content: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-portfolioId-2030071977": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 이름 */
                name: string;
                /** @description 설명 */
                description: string;
                /** @description 포트폴리오 ID */
                id: number;
                /** @description 총 매수 금액 */
                totalPurchaseAmount: number;
                /** @description 포트폴리오 구성 종목 목록 */
                items: (Record<string, never> | boolean | string | number)[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios1608975631": {
            /** @description 포트폴리오 이름 */
            name: string;
            /** @description 포트폴리오 설명 */
            description: string;
            items?: {
                /** @description 종목 심볼 */
                symbol: string;
                /** @description 보유 수량 */
                quantity: number;
                /** @description 목표 비중 (%) */
                targetWeight: number;
                /** @description 통화 (KRW, USD) */
                currency: string;
                /** @description 평균 매수가 */
                purchasePrice: number;
                /** @description 자산 타입 (STOCK, CASH) */
                assetType: string;
            }[];
        };
        "api-v1-admin-health-440200854": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                components?: {
                    /** @description Kafka 메시지 브로커 상태 */
                    kafka: string;
                    /** @description Redis 캐시 상태 */
                    redis: string;
                    /** @description 데이터베이스 상태 */
                    db: string;
                };
                /** @description 전체 상태 (UP/DOWN) */
                status: string;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 응답 메시지 */
            message: string;
            /** @description 상세 에러 리스트 */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-watchlist-groups620445008": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 생성된 그룹 ID */
            data: number;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-watchlist-groups-groupId-items104135515": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 그룹 이름 */
                groupName: string;
                items?: {
                    /** @description 투자 메모 */
                    note: string;
                    /** @description 종목 티커 */
                    ticker: string;
                    /** @description 등락률 */
                    fluctuationRate: number;
                    /** @description 종목명 */
                    name: string;
                    /** @description RSI 지표 */
                    rsi: number;
                    /** @description 현재가 */
                    currentPrice: number;
                    /** @description AI 한줄 분석 */
                    aiInsight: string;
                    /** @description RSI 상태 */
                    rsiStatus: string;
                }[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-1624336831": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 생성된 포트폴리오 ID */
            data: number;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-portfolioId-analysis-valuation1418848225": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 총 수익률 (%) */
                totalReturnRate: number;
                /** @description 당일 수익률 (%) */
                dailyReturnRate: number;
                /** @description 총 평가 손익 */
                totalProfitLoss: number;
                /** @description 당일 평가 손익 */
                dailyProfitLoss: number;
                /** @description 샤프 지수 */
                sharpeRatio: number;
                /** @description 최대 낙폭 (MDD) */
                mdd: number;
                /** @description 총 매수 금액 */
                totalPurchaseAmount: number;
                /** @description 현재 총 자산 가치 */
                currentTotalValue: number;
                /** @description 베타 계수 */
                beta: number;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        /** SectorSupplyResponse */
        SectorSupplyResponse: {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 섹터 수급 리스트 */
            data: {
                /** @description 기관 연속 매수 일수 */
                instConsecutiveBuyDays: number;
                /** @description 외국인 순매수 금액 */
                netForeignBuyAmount: number;
                /** @description 외국인 연속 매수 일수 */
                foreignConsecutiveBuyDays: number;
                /** @description 섹터 코드 */
                sectorCode: string;
                /** @description 기관 순매수 금액 */
                netInstBuyAmount: number;
                /** @description 섹터명 */
                sectorName: string;
            }[];
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-portfolioId-analysis-correlation-116670467": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 종목별 상관관계 행렬 데이터 (가변 구조) */
            data: Record<string, never>;
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-watchlist-groups-groupId-items-ticker-note-700261579": {
            /** @description 수정할 메모 내용 */
            note: string;
        };
        "api-v1-stocks-search-history2125272725": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            /** @description 최근 검색어 목록 */
            data: (Record<string, never> | boolean | string | number)[];
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-stocks-ticker-returns-1850814825": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 벤치마크 수익률 (%) */
                benchmarkReturnRate: number;
                /** @description 조회 기간 */
                period: string;
                /** @description 티커 */
                ticker: string;
                /** @description 종목 수익률 (%) */
                stockReturnRate: number;
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
        "api-v1-portfolios-portfolioId-analysis-rebalancing1494527279": {
            /** @description 비즈니스 상세 코드 */
            code: string;
            data?: {
                /** @description 총 자산 가치 */
                totalValue: number;
                items?: {
                    /** @description 종목 심볼 */
                    symbol: string;
                    /** @description 현재 비중 (%) */
                    currentWeight: number;
                    /** @description 비중 차이 (%p) */
                    diffWeight: number;
                    /** @description 현재가 */
                    currentPrice: number;
                    /** @description 목표 비중 (%) */
                    targetWeight: number;
                    /** @description 예상 매매 금액 */
                    expectedTradeAmount: number;
                    /** @description 권장 보유 수량 */
                    recommendedQuantity: number;
                    /** @description 현재 보유 수량 */
                    currentQuantity: number;
                }[];
            };
            /** @description 성공 여부 */
            success: boolean;
            /** @description 결과 메시지 */
            message: string;
            /** @description 상세 필드 에러 목록 (성공 시 빈 리스트) */
            errors?: (Record<string, never> | boolean | string | number)[] | null;
            /** @description 응답 시간 */
            timestamp: string;
            /** @description HTTP 상태 코드 */
            status: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "portfolio-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["api-v1-portfolios1608975631"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-1624336831"];
                };
            };
        };
    };
    "admin-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-admin-health-440200854"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Bearer Access Token
                 * @example Bearer {ACCESS_TOKEN}
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyDataResponse"];
                };
            };
        };
    };
    "auth-reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReissueRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReissueResponse"];
                };
            };
        };
    };
    "portfolio-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 포트폴리오 ID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-portfolioId-2030071977"];
                };
            };
        };
    };
    "stock-new-listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-stocks-new-listings562932331"];
                };
            };
        };
    };
    "stock-popular-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-stocks-popular-search-808622291"];
                };
            };
        };
    };
    "stock-search": {
        parameters: {
            query: {
                /** @description 검색어 (티커 또는 종목명) */
                keyword: string;
                /** @description 마켓 타입 (KOSPI, KOSDAQ 등) */
                marketType?: string;
                /** @description 종목 상태 (ACTIVE, HALTED 등) */
                status?: string;
                /** @description 페이지 번호 (0부터 시작) */
                page?: string;
                /** @description 페이지 사이즈 */
                size?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-stocks-search-1069080236"];
                };
            };
        };
    };
    "watchlist-group-list": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Bearer Access Token
                 * @example Bearer {ACCESS_TOKEN}
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-watchlist-groups15903716"];
                };
            };
        };
    };
    "watchlist-group-create": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Bearer Access Token
                 * @example Bearer {ACCESS_TOKEN}
                 */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["api-v1-watchlist-groups288370516"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-watchlist-groups620445008"];
                };
            };
        };
    };
    "sector-ranking": {
        parameters: {
            query?: {
                /** @description 조회 날짜 (yyyy-MM-dd) */
                date?: string;
                /** @description 시장 구분 (KOSPI, KOSDAQ) */
                marketType?: string;
                /** @description 조회 개수 */
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorRankingResponse"];
                };
            };
        };
    };
    "sector-supply": {
        parameters: {
            query?: {
                /** @description 조회 날짜 (yyyy-MM-dd) */
                date?: string;
                /** @description 시장 구분 (KOSPI, KOSDAQ) */
                marketType?: string;
                /** @description 조회 개수 */
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorSupplyResponse"];
                };
            };
        };
    };
    "sector-detail": {
        parameters: {
            query?: {
                /** @description 조회 날짜 (yyyy-MM-dd) */
                date?: string;
            };
            header?: never;
            path: {
                /** @description 섹터 코드 */
                sectorCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorDetailResponse"];
                };
            };
        };
    };
    "stock-search-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-stocks-search-history2125272725"];
                };
            };
        };
    };
    "stock-search-history-delete": {
        parameters: {
            query: {
                /** @description 삭제할 검색어 */
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["api-v1-stocks-search-history486549215"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyDataResponse"];
                };
            };
        };
    };
    "stock-returns": {
        parameters: {
            query: {
                /** @description 조회 기간 (1W, 1M, 1Y 등) */
                period: string;
            };
            header?: never;
            path: {
                /** @description 종목 티커 */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-stocks-ticker-returns-1850814825"];
                };
            };
        };
    };
    "portfolio-advice-latest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 포트폴리오 ID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-portfolioId-advice-latest-337529530"];
                };
            };
        };
    };
    "portfolio-analysis-backtest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 포트폴리오 ID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["api-v1-stocks-search-history486549215"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-portfolioId-analysis-backtest695967913"];
                };
            };
        };
    };
    "portfolio-analysis-correlation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 포트폴리오 ID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-portfolioId-analysis-correlation-116670467"];
                };
            };
        };
    };
    "portfolio-analysis-diversification": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 포트폴리오 ID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-portfolioId-analysis-diversification-1682980467"];
                };
            };
        };
    };
    "portfolio-analysis-rebalancing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 포트폴리오 ID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-portfolioId-analysis-rebalancing1494527279"];
                };
            };
        };
    };
    "portfolio-analysis-value": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 포트폴리오 ID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-portfolios-portfolioId-analysis-valuation1418848225"];
                };
            };
        };
    };
    "stock-search-history-clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyDataResponse"];
                };
            };
        };
    };
    "stock-price-history": {
        parameters: {
            query?: {
                /** @description 조회 기간 (1W, 1M, 1Y, ALL 등) */
                period?: string;
                /** @description 데이터 주기 (DAILY, WEEKLY, MONTHLY) */
                frequency?: string;
                /** @description 벤치마크 포함 여부 */
                includeBenchmark?: string;
            };
            header?: never;
            path: {
                /** @description 종목 티커 */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-stocks-ticker-prices-history-112452904"];
                };
            };
        };
    };
    "watchlist-item-list": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Bearer Access Token
                 * @example Bearer {ACCESS_TOKEN}
                 */
                Authorization: string;
            };
            path: {
                /** @description 그룹 ID */
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["api-v1-watchlist-groups-groupId-items104135515"];
                };
            };
        };
    };
    "watchlist-item-add": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Bearer Access Token
                 * @example Bearer {ACCESS_TOKEN}
                 */
                Authorization: string;
            };
            path: {
                /** @description 그룹 ID */
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["api-v1-watchlist-groups-groupId-items-775687594"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyDataResponse"];
                };
            };
        };
    };
    "watchlist-item-remove": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Bearer Access Token
                 * @example Bearer {ACCESS_TOKEN}
                 */
                Authorization: string;
            };
            path: {
                /** @description 그룹 ID */
                groupId: string;
                /** @description 종목 티커 */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyDataResponse"];
                };
            };
        };
    };
    "watchlist-item-note-update": {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Bearer Access Token
                 * @example Bearer {ACCESS_TOKEN}
                 */
                Authorization: string;
            };
            path: {
                /** @description 그룹 ID */
                groupId: string;
                /** @description 종목 티커 */
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["api-v1-watchlist-groups-groupId-items-ticker-note-700261579"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptyDataResponse"];
                };
            };
        };
    };
}
